subroutine help
    print*,'if mode=0 get 合并二十面体的取向:use change-ort-new newortfile mode=0 ort1name ort2name....... '
    print*,'if mode=6 get 合并对称失配的取向 :use change-ort-new newortfile mode=6 ort1name ort2name....... '
    print*,'if mode=1 get 二十面体取向中心减半:ues change-ort-new newortfile mode=1 oldname'
    print*,'if mode=2 get 二十面体中心扩大两倍[bin2 to mrcs]: use change-ort-new newortfile mode=2 oldname'
    print*,'if mode=8 get 二十面体中心扩大两倍[bin4 to bin2]: use change-ort-new newortfile mode=8 oldname'
    print*,'if mode=3 get 相位残差取余弦值: use change-ort-new newortfile mode=3 oldname'
    print*,'if mode=4 get 欠焦值取平均df=(df1+df2)/2.0: use change-ort-new newortfile mode=4 oldname'
    print*,'if mode=5 get 挑选中心（x or y)小于30.0 且相位残差小于50.0的取向(二十面体取向）'
    print*,           ':use change-ort-new newortfile mode=5 oldname'
    print*,'if mode=7 get 得到-phi的取向: use change-ort-new newortfile mode=7 oldname'
    print*,'if mode=9 get 得到-phi的取向[old format to new format]: use change-ort-new newortfile mode=9 oldname'
    print*,'if mode=10 get -y,-x: use change-ort-new newortfile mode=10 oldname'
    print*,'if mode=11 get 1-pr: use change-ort-new newortfile mode=11 oldname'
    print*,'if mode=12 get 统计来源于同一张图片的颗粒: use change-ort-new newortfile mode=12 oldname1 oldname2-only temp'
    print*,'if mode=13 get loc_search ort : use change-ort-new newortfile mode=13 oldname'
    print*,'if mode=14 get 局部取向中心减半: use change-ort-new newortfile mode=14 oldname'
    print*,'if mode=15 get 局部取向中心扩大两倍: use change-ort-new newortfile mode=15 oldname'
    print*,'if mode=16 get 获得Ck对称性倍数的取向: use change-ort-new newortfile mode=16 oldname'
    print*,'if mode=17 get 局部取向的挑选: use change-ort-new pick-good-ort mode=17 oldname pick-bad-ort'
    print*,'if mode=18 get 对称失配取向的挑选: use change-ort-new pick-good-ort mode=18 oldname pick-bad-ort'
    print*,'if mode=19 get 局部取向中心重置: use change-ort-new newortfile mode=19 oldortfile'
    print*,'if mode=20 get 局部取向重新框取颗粒配合local_box一起使用:'
    print*,'use change-ort-new newortfile mode=20 oldortfile'
    print*,'if mode=21 挑选mode=17挑出来的来自同一个颗粒的所有局部取向'
    print*,'use change-ort-new newortfile mode=21 local-all.dat local-pick.dat'
    print*,'if mode=22 将欠焦值乘以一万或者除以一万'
    print*,'use change-ort-new newortfile mode=22 oldortfile'
    print*,'mode=4 and mode=6 mode=11 mode=18 date format are :'
    print*,'a54,i8,f10.4,f10.4,f10.4,f10.4,f10.4,f10.4,i12,i6,f10.4,f10.4,f10.4'
    print*,'mode=14-21,execpt mode=18'
    print*,'a64,I9,F10.4,F10.4,F10.4,F10.4,F10.4,F10.4,I11,I7,F15.4,F15.4,F10.4, &
           i9,i6,i6,  &
           f10.4,f10.4,f10.4,  &
           f10.4,f10.4,f11.4,f10.4'

    print*,'another date format are :'
    print*,'a54,i8,f10.4,f10.4,f10.4,f10.4,f10.4,f10.4,i12,i6,f10.4,f10.4,f10.4,f10.4,f10.4,f10.4,f10.4,f10.4,f10.4'
end
