        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 01 12:00:43 2019
        MODULE CALC_RANDORT_2F__genmod
          INTERFACE 
            SUBROUTINE CALC_RANDORT_2F
            END SUBROUTINE CALC_RANDORT_2F
          END INTERFACE 
        END MODULE CALC_RANDORT_2F__genmod
