        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 01 11:43:45 2019
        MODULE ICOS2F_OPERATION_MATRIX__genmod
          INTERFACE 
            SUBROUTINE ICOS2F_OPERATION_MATRIX(R,N)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: R(3,3,N)
            END SUBROUTINE ICOS2F_OPERATION_MATRIX
          END INTERFACE 
        END MODULE ICOS2F_OPERATION_MATRIX__genmod
