        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 01 11:43:45 2019
        MODULE INIT_RANDOM_SEED_USE_TIMER__genmod
          INTERFACE 
            SUBROUTINE INIT_RANDOM_SEED_USE_TIMER
            END SUBROUTINE INIT_RANDOM_SEED_USE_TIMER
          END INTERFACE 
        END MODULE INIT_RANDOM_SEED_USE_TIMER__genmod
