        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 01 12:00:43 2019
        MODULE INPUTPARS__genmod
          INTERFACE 
            SUBROUTINE INPUTPARS
            END SUBROUTINE INPUTPARS
          END INTERFACE 
        END MODULE INPUTPARS__genmod
