        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 01 12:01:36 2019
        MODULE LOAD_ORIGINAL_ORTCENT__genmod
          INTERFACE 
            SUBROUTINE LOAD_ORIGINAL_ORTCENT
            END SUBROUTINE LOAD_ORIGINAL_ORTCENT
          END INTERFACE 
        END MODULE LOAD_ORIGINAL_ORTCENT__genmod
