        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 01 14:21:52 2019
        MODULE TRANSFORM_ORT_2FTO5F__genmod
          INTERFACE 
            SUBROUTINE TRANSFORM_ORT_2FTO5F
            END SUBROUTINE TRANSFORM_ORT_2FTO5F
          END INTERFACE 
        END MODULE TRANSFORM_ORT_2FTO5F__genmod
