subroutine help
print*,'ICOShedral virus data PROCess (ICOSPROC) of cryo-electrom.'
print*,'Usage:icosprocess_mismatch <mode=[1]> [apix=<1.0>] [result3d=map3d.mrc] [imgstck=img.stck] '
print*,'[newortfile=<newort.dat>] [minRes=<300>] [maxRes=<8>] [imgmask=<FFTsize*apix/2>]'
print*,'[model3d=<map3d.mrc>] [PR_threshold=<0.8>] [PR_threshold_h=<1>] [Ncycle=6] [searchstep=<2.0> [sym=<c1>] [first=<1>]'
print*,'[last=<mrc%nz>] [applyCTF=<n>] [vol=<300>] [Cs=<2.7>] [ampwg=<0.07>] [Bfactor=<.0>] [FSC=y][PAD=1]'

print*,'<mode=[1]>:0:genomeimgstck abstract'
print*,'need parameters: model3d,result3d<genomestck>,imgstck,geneFFTsize,applyCTF<all parameters>,'
print*,'                 maxRes,ortfile,newortfile,capsid_innerR,capsid_outerR'
print*,'           1:random 3D reconstruction'
print*,'need parameters: result3d,sym,ortfile,maxRes,imgmask,applyCTF,imgstck<y.or.n>,PR_threshold'
print*,'           2: 3D reconstruction'
print*,'need parameters: result3d,sym,ortfile,maxRes,imgmask,applyCTF,imgstck<y.or.n>,PR_threshold'
print*,'           3:align_core by cross-correlation'
print*,'need parameters: model3d,ortfile,newortfile,maxRes,imgmask,applyCTF,imgstck<y.or.n>,first,last'
print*,'           4:img2d_stck pakege'

print*,'           5:calculate cent'
print*,'           6:align_core by phase-correlation'
print*,'need parameters: model3d,ortfile,newortfile,maxRes,imgmask,applyCTF,imgstck<y.or.n>,first,last'
print*,'           7:local align_vertex '
print*,'need parameters: model3d,ortfile,newortfile,maxRes,imgmask,applyCTF,imgstck<y.or.n>,first,last,PAD,particle_radius'
print*,'                 ,loc_box,pr_cc,Ncycle,searchstep'
print*,'           8:12vertex local or whole align_vertex'
print*,'           9:loc_search by align_core 5-Equivalent orientation '
print*,'need parameters: model3d,ortfile,newortfile,maxRes,imgmask,applyCTF,imgstck<y.or.n>,first,last,PAD,'
print*,'                 pr_cc,Ncycle,searchstep'
print*,'           10:loc_search '
print*,'           11:phase_redsiual'
print*,'           12:map-clip[only need model3d result3d '
print*,'           13:fen lei rawimg[need ortfile newortfile imgmask ]'
print*,'           14:tail_mask[only need model3d core3d result3d'
print*,'<ortfile=ort.dat>:input orientation and center file'
print*,'[apix=<1.0>]'
print*,'[result3d=map3d.mrc]: reconstruction result.'
print*,'[newortfile=newort.dat]: new orientation and center file.'
print*,'[capsid_innerR=<244>'
print*,'[capsid_outerR=<270.5>'
print*,'[minRes=<300>]: min resolution for orientation determination (angstrom).'
print*,'[maxRes=<8>: target resolution for reconstruction and orientation determination (angstrom).'
print*,'[imgmask=<FFTsize*apix/2>]: mask radius for 2D image (angstrom).'
print*,'[model3d=<map3d.mrc>]: 3D model use for orientation and center determination'
print*,'[core3d=<map3d.mrc>]: core3D model use for orientation and center determination  '
print*,'[PR_threshold=<0.8>]: the phase threshold for reconstruction'
print*,'[PR_threshold_h=<1.0>]: the phase threshold for reconstruction'
print*,'[Ncycle=6]: cycle number for local refinement.'
print*,'[centbound=fftsize/4.0'
print*,'[sym=<c1>]: icos,c1,c12,c15'
print*,'[geneFFTsize=FFTsize'
print*,'[first=<1>]'
print*,'[last=<1000>]'
print*,'[applyCTF=<y>]'
print*,'[vol=<300>]'
print*,'[Cs=<2.7>]'
print*,'[ampwg=<0.07>]'
print*,'[Bfactor=<.0>]'
print*,'[subrec=y]:sub reconstruction'
print*,'[FSC=y]:calculate FSC between odd and even particle,and add FSC weight for reconstruction'
print*,'[loc_box=<48>]'
print*,'[particle_radius=<300>'
print*,'[PAD=<1>'
print*,'[clipsize=<fftsize>'
print*,'[pr_cc=n]:if need 1-pr then you should input y '
print*,'Hongrong Liu and Wenyuan Chen, HUNNU, AM 10:30 26/11/2018 '
return


end

