!存储各输入参数

subroutine input_parameters
use common_icosproc
    implicit none
    coeff(1) ='apix'
    coeff(2) ='minRes'
    coeff(3) ='maxRes'
    coeff(4) ='imgmask'
    coeff(5) ='first'
    coeff(6) ='last'
    coeff(7) ='applyCTF'
    coeff(8) ='Ncycle'
    coeff(9)='templatestck'
    coeff(10)='vol'
    coeff(11)='Cs'
    coeff(12)='Bfactor'
    coeff(13)='ampwg'
    coeff(14)='PR_threshold'
    coeff(15)='sym'
    coeff(16)='result3d'
    coeff(17)='mode'
    coeff(18)='newortfile'
    coeff(19)='model3d'
    coeff(20)='templateort'
    coeff(21)='searchstep'
    coeff(22)='realspaceavg'
    coeff(23)='ortfile'
    coeff(24)='recISAF'
    coeff(25)='imask'
    coeff(26)='subrec'
    coeff(27)='FSC'
    coeff(28)='FRC'
    coeff(29)='capsid_innerR'
    coeff(30)='capsid_outerR'
    coeff(31)='core_radius'
    coeff(32)='capsidmodel'
    coeff(33)='coremodel'
    coeff(34)='genomeimgstck'
    coeff(35)='geneFFTsize'
    coeff(36)='outputprojstck'
    coeff(37)='outputrawimgstck'
    coeff(38)='imgstck'
    coeff(39)='centshift'
    coeff(40)='centbound'
    coeff(41)='FFTsize'
    coeff(42)='newimgstck'
    coeff(43)='PR_threshold_h'
    coeff(44)='particle_radius'
    coeff(45)='loc_box'
    coeff(46)='core3d'
    coeff(47)='PAD'
    coeff(48)='clipsize'
    coeff(49)='pr_cc'


    proc2d%applyCTF    ='y'
    proc2d%imgmask     ='n'
    proc2d%FRC         ='n'
    proc2d%geneFFTsize ='n'
    proc2d%clipsize    ='n'
    proc2d%centshift   ='n'
    proc2d%imgstck     ='n'
    proc3d%realspaceavg='n'
    proc3d%model3d     ='n'
    proc3d%core3d      ='n'
    proc3d%templatestck='n'
    proc3d%templateort ='n'
    proc3d%recISAF     ='n'
    proc3d%imask       ='n'
    proc3d%subrec      ='n'
    proc3d%outputprojstck='n'
    proc3d%outputrawimgstck='n'
    proc2d%newimgstck  ='n'
    sym='c1'
    proc2d%pr_cc='n'

    centbound=200

    return
end

